// export const exerciseBack = [
//   {
//     bodyPart: "back",
//     equipment: "cable",
//     gifUrl: "https://v2.exercisedb.io/image/I4XMjCBFhqaGoJ",
//     id: "0007",
//     name: "alternate lateral pulldown",
//     target: "lats",
//     secondaryMuscles: ["biceps", "rhomboids"],
//     instructions: [
//       "Sit on the cable machine with your back straight and feet flat on the ground.",
//       "Grasp the handles with an overhand grip, slightly wider than shoulder-width apart.",
//       "Lean back slightly and pull the handles towards your chest, squeezing your shoulder blades together.",
//       "Pause for a moment at the peak of the movement, then slowly release the handles back to the starting position.",
//       "Repeat for the desired number of repetitions.",
//     ],
//   },
//   {
//     bodyPart: "back",
//     equipment: "body weight",
//     gifUrl: "https://v2.exercisedb.io/image/IhSIJPWFEJU76Q",
//     id: "3293",
//     name: "archer pull up",
//     target: "lats",
//     secondaryMuscles: ["biceps", "forearms"],
//     instructions: [
//       "Start by hanging from a pull-up bar with an overhand grip, slightly wider than shoulder-width apart.",
//       "Engage your core and pull your shoulder blades down and back.",
//       "As you pull yourself up, bend one arm and bring your elbow towards your side, while keeping the other arm straight.",
//       "Continue pulling until your chin is above the bar and your bent arm is fully flexed.",
//       "Lower yourself back down with control, straightening the bent arm and repeating the movement on the other side.",
//       "Alternate sides with each repetition.",
//     ],
//   },
//   {
//     bodyPart: "back",
//     equipment: "leverage machine",
//     gifUrl: "https://v2.exercisedb.io/image/Js4jXbAEKYW8jz",
//     id: "0015",
//     name: "assisted parallel close grip pull-up",
//     target: "lats",
//     secondaryMuscles: ["biceps", "forearms"],
//     instructions: [
//       "Adjust the machine to your desired weight and height.",
//       "Place your hands on the parallel bars with a close grip, palms facing each other.",
//       "Hang from the bars with your arms fully extended and your feet off the ground.",
//       "Engage your back muscles and pull your body up towards the bars, keeping your elbows close to your body.",
//       "Continue pulling until your chin is above the bars.",
//       "Pause for a moment at the top, then slowly lower your body back down to the starting position.",
//       "Repeat for the desired number of repetitions.",
//     ],
//   },
//   {
//     bodyPart: "back",
//     equipment: "leverage machine",
//     gifUrl: "https://v2.exercisedb.io/image/zJzZxwHW1MBBi4",
//     id: "0017",
//     name: "assisted pull-up",
//     target: "lats",
//     secondaryMuscles: ["biceps", "forearms"],
//     instructions: [
//       "Adjust the machine to your desired weight and height settings.",
//       "Grasp the handles with an overhand grip, slightly wider than shoulder-width apart.",
//       "Hang with your arms fully extended and your feet off the ground.",
//       "Engage your back muscles and pull your body up towards the handles, keeping your elbows close to your body.",
//       "Continue pulling until your chin is above the handles.",
//       "Pause for a moment at the top, then slowly lower your body back down to the starting position.",
//       "Repeat for the desired number of repetitions.",
//     ],
//   },
//   {
//     bodyPart: "back",
//     equipment: "leverage machine",
//     gifUrl: "https://v2.exercisedb.io/image/kZGmWmtCz-wr59",
//     id: "1431",
//     name: "assisted standing chin-up",
//     target: "lats",
//     secondaryMuscles: ["biceps", "forearms"],
//     instructions: [
//       "Adjust the machine to your desired assistance level.",
//       "Stand on the foot platform and grip the handles with an overhand grip, slightly wider than shoulder-width apart.",
//       "Keep your chest up and shoulders back, engage your core, and slightly bend your knees.",
//       "Pull your body up by flexing your elbows and driving your elbows down towards your sides.",
//       "Continue pulling until your chin is above the bar.",
//       "Pause for a moment at the top, then slowly lower your body back down to the starting position.",
//       "Repeat for the desired number of repetitions.",
//     ],
//   },
//   {
//     bodyPart: "back",
//     equipment: "leverage machine",
//     gifUrl: "https://v2.exercisedb.io/image/5sokFlo35yBy59",
//     id: "1432",
//     name: "assisted standing pull-up",
//     target: "lats",
//     secondaryMuscles: ["biceps", "forearms"],
//     instructions: [
//       "Adjust the machine to your desired weight and height settings.",
//       "Stand facing the machine with your feet shoulder-width apart.",
//       "Grasp the handles with an overhand grip, slightly wider than shoulder-width apart.",
//       "Engage your lats and biceps, and pull yourself up towards the handles.",
//       "Pause for a moment at the top, squeezing your back muscles.",
//       "Slowly lower yourself back down to the starting position.",
//       "Repeat for the desired number of repetitions.",
//     ],
//   },
//   {
//     bodyPart: "back",
//     equipment: "stability ball",
//     gifUrl: "https://v2.exercisedb.io/image/9BUHP5bRnFhP-j",
//     id: "1314",
//     name: "back extension on exercise ball",
//     target: "spine",
//     secondaryMuscles: ["glutes", "hamstrings"],
//     instructions: [
//       "Place the stability ball on the ground and lie face down on top of it, with your hips resting on the ball and your feet against a wall or other stable surface.",
//       "Position your hands behind your head or crossed over your chest.",
//       "Engage your core and slowly lift your upper body off the ball, extending your back until your body forms a straight line from your head to your heels.",
//       "Pause for a moment at the top, then slowly lower your upper body back down to the starting position.",
//       "Repeat for the desired number of repetitions.",
//     ],
//   },
//   {
//     bodyPart: "back",
//     equipment: "body weight",
//     gifUrl: "https://v2.exercisedb.io/image/flhfZ18HrAZSKu",
//     id: "3297",
//     name: "back lever",
//     target: "upper back",
//     secondaryMuscles: ["biceps", "forearms", "core"],
//     instructions: [
//       "Start by hanging from a pull-up bar with an overhand grip, hands slightly wider than shoulder-width apart.",
//       "Engage your core and pull your shoulder blades down and back.",
//       "Bend your knees and tuck them towards your chest.",
//       "Slowly lift your legs up, keeping them straight, until your body is parallel to the ground.",
//       "Hold this position for a few seconds, then slowly lower your legs back down to the starting position.",
//       "Repeat for the desired number of repetitions.",
//     ],
//   },
//   {
//     bodyPart: "back",
//     equipment: "body weight",
//     gifUrl: "https://v2.exercisedb.io/image/nWVvuFyM0YNezC",
//     id: "1405",
//     name: "back pec stretch",
//     target: "lats",
//     secondaryMuscles: ["shoulders", "chest"],
//     instructions: [
//       "Stand tall with your feet shoulder-width apart.",
//       "Extend your arms straight out in front of you, parallel to the ground.",
//       "Cross your arms in front of your body, with your right arm over your left arm.",
//       "Interlock your fingers and rotate your palms away from your body.",
//       "Slowly raise your arms up and away from your body, feeling a stretch in your back and chest.",
//       "Hold the stretch for 15-30 seconds, then release.",
//       "Repeat on the opposite side.",
//     ],
//   },
//   {
//     bodyPart: "back",
//     equipment: "band",
//     gifUrl: "https://v2.exercisedb.io/image/A6-KFl2ZNIPvW7",
//     id: "0970",
//     name: "band assisted pull-up",
//     target: "lats",
//     secondaryMuscles: ["biceps", "forearms"],
//     instructions: [
//       "Attach the band to a pull-up bar or sturdy anchor point.",
//       "Step onto the band and grip the bar with your palms facing away from you, hands slightly wider than shoulder-width apart.",
//       "Hang with your arms fully extended, keeping your core engaged and your shoulders down and back.",
//       "Pull your body up towards the bar by squeezing your shoulder blades together and driving your elbows down towards your hips.",
//       "Continue pulling until your chin is above the bar, then slowly lower yourself back down to the starting position.",
//       "Repeat for the desired number of repetitions.",
//     ],
//   },
// ];

// export const exerciseChest = [
//   {
//     bodyPart: "chest",
//     equipment: "body weight",
//     gifUrl: "https://v2.exercisedb.io/image/Bi8xVYeWIyqo56",
//     id: "3294",
//     name: "archer push up",
//     target: "pectorals",
//     secondaryMuscles: ["triceps", "shoulders", "core"],
//     instructions: [
//       "Start in a push-up position with your hands slightly wider than shoulder-width apart.",
//       "Extend one arm straight out to the side, parallel to the ground.",
//       "Lower your body by bending your elbows, keeping your back straight and core engaged.",
//       "Push back up to the starting position.",
//       "Repeat on the other side, extending the opposite arm out to the side.",
//       "Continue alternating sides for the desired number of repetitions.",
//     ],
//   },
//   {
//     bodyPart: "chest",
//     equipment: "leverage machine",
//     gifUrl: "https://v2.exercisedb.io/image/fmdqpJ0us59Y9T",
//     id: "0009",
//     name: "assisted chest dip (kneeling)",
//     target: "pectorals",
//     secondaryMuscles: ["triceps", "shoulders"],
//     instructions: [
//       "Adjust the machine to your desired height and secure your knees on the pad.",
//       "Grasp the handles with your palms facing down and your arms fully extended.",
//       "Lower your body by bending your elbows until your upper arms are parallel to the floor.",
//       "Pause for a moment, then push yourself back up to the starting position.",
//       "Repeat for the desired number of repetitions.",
//     ],
//   },
//   {
//     bodyPart: "chest",
//     equipment: "assisted",
//     gifUrl: "https://v2.exercisedb.io/image/UwZ3IUi9CeHxSa",
//     id: "1716",
//     name: "assisted seated pectoralis major stretch with stability ball",
//     target: "pectorals",
//     secondaryMuscles: ["shoulders", "triceps"],
//     instructions: [
//       "Sit on a stability ball with your feet flat on the ground and your back straight.",
//       "Hold a stability ball with both hands and extend your arms straight out in front of you.",
//       "Slowly lower the stability ball towards your chest, feeling a stretch in your pectoral muscles.",
//       "Hold the stretch for a few seconds, then slowly return to the starting position.",
//       "Repeat for the desired number of repetitions.",
//     ],
//   },
//   {
//     bodyPart: "chest",
//     equipment: "leverage machine",
//     gifUrl: "https://v2.exercisedb.io/image/9sh8GAwoZtQeiv",
//     id: "2364",
//     name: "assisted wide-grip chest dip (kneeling)",
//     target: "pectorals",
//     secondaryMuscles: ["triceps", "shoulders"],
//     instructions: [
//       "Adjust the machine to your desired height and secure your knees on the pad.",
//       "Grasp the handles with a wide grip and keep your elbows slightly bent.",
//       "Lower your body by bending your elbows until your upper arms are parallel to the floor.",
//       "Push yourself back up to the starting position by extending your arms.",
//       "Repeat for the desired number of repetitions.",
//     ],
//   },
//   {
//     bodyPart: "chest",
//     equipment: "band",
//     gifUrl: "https://v2.exercisedb.io/image/ZacMbIJVdFcd-i",
//     id: "1254",
//     name: "band bench press",
//     target: "pectorals",
//     secondaryMuscles: ["triceps", "shoulders"],
//     instructions: [
//       "Lie flat on a bench with your feet flat on the ground and your back pressed against the bench.",
//       "Grasp the band handles with an overhand grip, slightly wider than shoulder-width apart.",
//       "Extend your arms fully, pushing the bands away from your chest.",
//       "Slowly lower the bands back down to your chest, keeping your elbows at a 90-degree angle.",
//       "Repeat for the desired number of repetitions.",
//     ],
//   },
//   {
//     bodyPart: "chest",
//     equipment: "band",
//     gifUrl: "https://v2.exercisedb.io/image/EzkN8409Qewbpa",
//     id: "0989",
//     name: "band one arm twisting chest press",
//     target: "pectorals",
//     secondaryMuscles: ["shoulders", "triceps"],
//     instructions: [
//       "Attach the band to a sturdy anchor point at chest height.",
//       "Stand with your side facing the anchor point and grab the band with one hand.",
//       "Step away from the anchor point to create tension in the band.",
//       "Position your feet shoulder-width apart and slightly bend your knees.",
//       "Bring your hand holding the band across your body, towards the opposite shoulder.",
//       "While maintaining tension in the band, push your hand forward and away from your body, extending your arm.",
//       "Slowly return to the starting position and repeat for the desired number of repetitions.",
//       "Switch sides and repeat the exercise with the other hand.",
//     ],
//   },
//   {
//     bodyPart: "chest",
//     equipment: "barbell",
//     gifUrl: "https://v2.exercisedb.io/image/L7vyesWgDz-LKH",
//     id: "0025",
//     name: "barbell bench press",
//     target: "pectorals",
//     secondaryMuscles: ["triceps", "shoulders"],
//     instructions: [
//       "Lie flat on a bench with your feet flat on the ground and your back pressed against the bench.",
//       "Grasp the barbell with an overhand grip slightly wider than shoulder-width apart.",
//       "Lift the barbell off the rack and hold it directly above your chest with your arms fully extended.",
//       "Lower the barbell slowly towards your chest, keeping your elbows tucked in.",
//       "Pause for a moment when the barbell touches your chest.",
//       "Push the barbell back up to the starting position by extending your arms.",
//       "Repeat for the desired number of repetitions.",
//     ],
//   },
//   {
//     bodyPart: "chest",
//     equipment: "barbell",
//     gifUrl: "https://v2.exercisedb.io/image/ieojiob5VojQdg",
//     id: "0033",
//     name: "barbell decline bench press",
//     target: "pectorals",
//     secondaryMuscles: ["triceps", "shoulders"],
//     instructions: [
//       "Lie on a decline bench with your feet secured and your head lower than your hips.",
//       "Grasp the barbell with an overhand grip slightly wider than shoulder-width apart.",
//       "Unrack the barbell and lower it slowly towards your chest, keeping your elbows tucked in.",
//       "Pause for a moment at the bottom, then push the barbell back up to the starting position.",
//       "Repeat for the desired number of repetitions.",
//     ],
//   },
//   {
//     bodyPart: "chest",
//     equipment: "barbell",
//     gifUrl: "https://v2.exercisedb.io/image/JjAqrrWu6WL98o",
//     id: "1255",
//     name: "barbell decline pullover",
//     target: "pectorals",
//     secondaryMuscles: ["triceps", "shoulders"],
//     instructions: [
//       "Lie down on a decline bench with your head lower than your hips and your feet secured.",
//       "Hold the barbell with a pronated grip (palms facing away from you) and your hands slightly wider than shoulder-width apart.",
//       "Extend your arms above your chest, keeping a slight bend in your elbows.",
//       "Lower the barbell in an arc motion behind your head, feeling a stretch in your chest and shoulders.",
//       "Pause for a moment, then return the barbell to the starting position by reversing the motion.",
//       "Repeat for the desired number of repetitions.",
//     ],
//   },
//   {
//     bodyPart: "chest",
//     equipment: "barbell",
//     gifUrl: "https://v2.exercisedb.io/image/RSf84MsQSpBsQQ",
//     id: "0036",
//     name: "barbell decline wide-grip press",
//     target: "pectorals",
//     secondaryMuscles: ["triceps", "shoulders"],
//     instructions: [
//       "Lie on a decline bench with your feet secured and your head lower than your hips.",
//       "Grasp the barbell with a wide grip, slightly wider than shoulder-width apart.",
//       "Lower the barbell to your chest, keeping your elbows out to the sides.",
//       "Push the barbell back up to the starting position, fully extending your arms.",
//       "Repeat for the desired number of repetitions.",
//     ],
//   },
// ];

export const exercises = {
  back: [
    {
      bodyPart: "back",
      equipment: "cable",
      gifUrl: "https://v2.exercisedb.io/image/I4XMjCBFhqaGoJ",
      id: "0007",
      name: "alternate lateral pulldown",
      target: "lats",
      secondaryMuscles: ["biceps", "rhomboids"],
      instructions: [
        "Sit on the cable machine with your back straight and feet flat on the ground.",
        "Grasp the handles with an overhand grip, slightly wider than shoulder-width apart.",
        "Lean back slightly and pull the handles towards your chest, squeezing your shoulder blades together.",
        "Pause for a moment at the peak of the movement, then slowly release the handles back to the starting position.",
        "Repeat for the desired number of repetitions.",
      ],
    },
    {
      bodyPart: "back",
      equipment: "body weight",
      gifUrl: "https://v2.exercisedb.io/image/IhSIJPWFEJU76Q",
      id: "3293",
      name: "archer pull up",
      target: "lats",
      secondaryMuscles: ["biceps", "forearms"],
      instructions: [
        "Start by hanging from a pull-up bar with an overhand grip, slightly wider than shoulder-width apart.",
        "Engage your core and pull your shoulder blades down and back.",
        "As you pull yourself up, bend one arm and bring your elbow towards your side, while keeping the other arm straight.",
        "Continue pulling until your chin is above the bar and your bent arm is fully flexed.",
        "Lower yourself back down with control, straightening the bent arm and repeating the movement on the other side.",
        "Alternate sides with each repetition.",
      ],
    },
    {
      bodyPart: "back",
      equipment: "leverage machine",
      gifUrl: "https://v2.exercisedb.io/image/Js4jXbAEKYW8jz",
      id: "0015",
      name: "assisted parallel close grip pull-up",
      target: "lats",
      secondaryMuscles: ["biceps", "forearms"],
      instructions: [
        "Adjust the machine to your desired weight and height.",
        "Place your hands on the parallel bars with a close grip, palms facing each other.",
        "Hang from the bars with your arms fully extended and your feet off the ground.",
        "Engage your back muscles and pull your body up towards the bars, keeping your elbows close to your body.",
        "Continue pulling until your chin is above the bars.",
        "Pause for a moment at the top, then slowly lower your body back down to the starting position.",
        "Repeat for the desired number of repetitions.",
      ],
    },
    {
      bodyPart: "back",
      equipment: "leverage machine",
      gifUrl: "https://v2.exercisedb.io/image/zJzZxwHW1MBBi4",
      id: "0017",
      name: "assisted pull-up",
      target: "lats",
      secondaryMuscles: ["biceps", "forearms"],
      instructions: [
        "Adjust the machine to your desired weight and height settings.",
        "Grasp the handles with an overhand grip, slightly wider than shoulder-width apart.",
        "Hang with your arms fully extended and your feet off the ground.",
        "Engage your back muscles and pull your body up towards the handles, keeping your elbows close to your body.",
        "Continue pulling until your chin is above the handles.",
        "Pause for a moment at the top, then slowly lower your body back down to the starting position.",
        "Repeat for the desired number of repetitions.",
      ],
    },
    {
      bodyPart: "back",
      equipment: "leverage machine",
      gifUrl: "https://v2.exercisedb.io/image/kZGmWmtCz-wr59",
      id: "1431",
      name: "assisted standing chin-up",
      target: "lats",
      secondaryMuscles: ["biceps", "forearms"],
      instructions: [
        "Adjust the machine to your desired assistance level.",
        "Stand on the foot platform and grip the handles with an overhand grip, slightly wider than shoulder-width apart.",
        "Keep your chest up and shoulders back, engage your core, and slightly bend your knees.",
        "Pull your body up by flexing your elbows and driving your elbows down towards your sides.",
        "Continue pulling until your chin is above the bar.",
        "Pause for a moment at the top, then slowly lower your body back down to the starting position.",
        "Repeat for the desired number of repetitions.",
      ],
    },
    {
      bodyPart: "back",
      equipment: "leverage machine",
      gifUrl: "https://v2.exercisedb.io/image/5sokFlo35yBy59",
      id: "1432",
      name: "assisted standing pull-up",
      target: "lats",
      secondaryMuscles: ["biceps", "forearms"],
      instructions: [
        "Adjust the machine to your desired weight and height settings.",
        "Stand facing the machine with your feet shoulder-width apart.",
        "Grasp the handles with an overhand grip, slightly wider than shoulder-width apart.",
        "Engage your lats and biceps, and pull yourself up towards the handles.",
        "Pause for a moment at the top, squeezing your back muscles.",
        "Slowly lower yourself back down to the starting position.",
        "Repeat for the desired number of repetitions.",
      ],
    },
    {
      bodyPart: "back",
      equipment: "stability ball",
      gifUrl: "https://v2.exercisedb.io/image/9BUHP5bRnFhP-j",
      id: "1314",
      name: "back extension on exercise ball",
      target: "spine",
      secondaryMuscles: ["glutes", "hamstrings"],
      instructions: [
        "Place the stability ball on the ground and lie face down on top of it, with your hips resting on the ball and your feet against a wall or other stable surface.",
        "Position your hands behind your head or crossed over your chest.",
        "Engage your core and slowly lift your upper body off the ball, extending your back until your body forms a straight line from your head to your heels.",
        "Pause for a moment at the top, then slowly lower your upper body back down to the starting position.",
        "Repeat for the desired number of repetitions.",
      ],
    },
    {
      bodyPart: "back",
      equipment: "body weight",
      gifUrl: "https://v2.exercisedb.io/image/flhfZ18HrAZSKu",
      id: "3297",
      name: "back lever",
      target: "upper back",
      secondaryMuscles: ["biceps", "forearms", "core"],
      instructions: [
        "Start by hanging from a pull-up bar with an overhand grip, hands slightly wider than shoulder-width apart.",
        "Engage your core and pull your shoulder blades down and back.",
        "Bend your knees and tuck them towards your chest.",
        "Slowly lift your legs up, keeping them straight, until your body is parallel to the ground.",
        "Hold this position for a few seconds, then slowly lower your legs back down to the starting position.",
        "Repeat for the desired number of repetitions.",
      ],
    },
    {
      bodyPart: "back",
      equipment: "body weight",
      gifUrl: "https://v2.exercisedb.io/image/nWVvuFyM0YNezC",
      id: "1405",
      name: "back pec stretch",
      target: "lats",
      secondaryMuscles: ["shoulders", "chest"],
      instructions: [
        "Stand tall with your feet shoulder-width apart.",
        "Extend your arms straight out in front of you, parallel to the ground.",
        "Cross your arms in front of your body, with your right arm over your left arm.",
        "Interlock your fingers and rotate your palms away from your body.",
        "Slowly raise your arms up and away from your body, feeling a stretch in your back and chest.",
        "Hold the stretch for 15-30 seconds, then release.",
        "Repeat on the opposite side.",
      ],
    },
    {
      bodyPart: "back",
      equipment: "band",
      gifUrl: "https://v2.exercisedb.io/image/A6-KFl2ZNIPvW7",
      id: "0970",
      name: "band assisted pull-up",
      target: "lats",
      secondaryMuscles: ["biceps", "forearms"],
      instructions: [
        "Attach the band to a pull-up bar or sturdy anchor point.",
        "Step onto the band and grip the bar with your palms facing away from you, hands slightly wider than shoulder-width apart.",
        "Hang with your arms fully extended, keeping your core engaged and your shoulders down and back.",
        "Pull your body up towards the bar by squeezing your shoulder blades together and driving your elbows down towards your hips.",
        "Continue pulling until your chin is above the bar, then slowly lower yourself back down to the starting position.",
        "Repeat for the desired number of repetitions.",
      ],
    },
  ],
  chest: [
    {
      bodyPart: "chest",
      equipment: "body weight",
      gifUrl: "https://v2.exercisedb.io/image/Bi8xVYeWIyqo56",
      id: "3294",
      name: "archer push up",
      target: "pectorals",
      secondaryMuscles: ["triceps", "shoulders", "core"],
      instructions: [
        "Start in a push-up position with your hands slightly wider than shoulder-width apart.",
        "Extend one arm straight out to the side, parallel to the ground.",
        "Lower your body by bending your elbows, keeping your back straight and core engaged.",
        "Push back up to the starting position.",
        "Repeat on the other side, extending the opposite arm out to the side.",
        "Continue alternating sides for the desired number of repetitions.",
      ],
    },
    {
      bodyPart: "chest",
      equipment: "leverage machine",
      gifUrl: "https://v2.exercisedb.io/image/fmdqpJ0us59Y9T",
      id: "0009",
      name: "assisted chest dip (kneeling)",
      target: "pectorals",
      secondaryMuscles: ["triceps", "shoulders"],
      instructions: [
        "Adjust the machine to your desired height and secure your knees on the pad.",
        "Grasp the handles with your palms facing down and your arms fully extended.",
        "Lower your body by bending your elbows until your upper arms are parallel to the floor.",
        "Pause for a moment, then push yourself back up to the starting position.",
        "Repeat for the desired number of repetitions.",
      ],
    },
    {
      bodyPart: "chest",
      equipment: "assisted",
      gifUrl: "https://v2.exercisedb.io/image/UwZ3IUi9CeHxSa",
      id: "1716",
      name: "assisted seated pectoralis major stretch with stability ball",
      target: "pectorals",
      secondaryMuscles: ["shoulders", "triceps"],
      instructions: [
        "Sit on a stability ball with your feet flat on the ground and your back straight.",
        "Hold a stability ball with both hands and extend your arms straight out in front of you.",
        "Slowly lower the stability ball towards your chest, feeling a stretch in your pectoral muscles.",
        "Hold the stretch for a few seconds, then slowly return to the starting position.",
        "Repeat for the desired number of repetitions.",
      ],
    },
    {
      bodyPart: "chest",
      equipment: "leverage machine",
      gifUrl: "https://v2.exercisedb.io/image/9sh8GAwoZtQeiv",
      id: "2364",
      name: "assisted wide-grip chest dip (kneeling)",
      target: "pectorals",
      secondaryMuscles: ["triceps", "shoulders"],
      instructions: [
        "Adjust the machine to your desired height and secure your knees on the pad.",
        "Grasp the handles with a wide grip and keep your elbows slightly bent.",
        "Lower your body by bending your elbows until your upper arms are parallel to the floor.",
        "Push yourself back up to the starting position by extending your arms.",
        "Repeat for the desired number of repetitions.",
      ],
    },
    {
      bodyPart: "chest",
      equipment: "band",
      gifUrl: "https://v2.exercisedb.io/image/ZacMbIJVdFcd-i",
      id: "1254",
      name: "band bench press",
      target: "pectorals",
      secondaryMuscles: ["triceps", "shoulders"],
      instructions: [
        "Lie flat on a bench with your feet flat on the ground and your back pressed against the bench.",
        "Grasp the band handles with an overhand grip, slightly wider than shoulder-width apart.",
        "Extend your arms fully, pushing the bands away from your chest.",
        "Slowly lower the bands back down to your chest, keeping your elbows at a 90-degree angle.",
        "Repeat for the desired number of repetitions.",
      ],
    },
    {
      bodyPart: "chest",
      equipment: "band",
      gifUrl: "https://v2.exercisedb.io/image/EzkN8409Qewbpa",
      id: "0989",
      name: "band one arm twisting chest press",
      target: "pectorals",
      secondaryMuscles: ["shoulders", "triceps"],
      instructions: [
        "Attach the band to a sturdy anchor point at chest height.",
        "Stand with your side facing the anchor point and grab the band with one hand.",
        "Step away from the anchor point to create tension in the band.",
        "Position your feet shoulder-width apart and slightly bend your knees.",
        "Bring your hand holding the band across your body, towards the opposite shoulder.",
        "While maintaining tension in the band, push your hand forward and away from your body, extending your arm.",
        "Slowly return to the starting position and repeat for the desired number of repetitions.",
        "Switch sides and repeat the exercise with the other hand.",
      ],
    },
    {
      bodyPart: "chest",
      equipment: "barbell",
      gifUrl: "https://v2.exercisedb.io/image/L7vyesWgDz-LKH",
      id: "0025",
      name: "barbell bench press",
      target: "pectorals",
      secondaryMuscles: ["triceps", "shoulders"],
      instructions: [
        "Lie flat on a bench with your feet flat on the ground and your back pressed against the bench.",
        "Grasp the barbell with an overhand grip slightly wider than shoulder-width apart.",
        "Lift the barbell off the rack and hold it directly above your chest with your arms fully extended.",
        "Lower the barbell slowly towards your chest, keeping your elbows tucked in.",
        "Pause for a moment when the barbell touches your chest.",
        "Push the barbell back up to the starting position by extending your arms.",
        "Repeat for the desired number of repetitions.",
      ],
    },
    {
      bodyPart: "chest",
      equipment: "barbell",
      gifUrl: "https://v2.exercisedb.io/image/ieojiob5VojQdg",
      id: "0033",
      name: "barbell decline bench press",
      target: "pectorals",
      secondaryMuscles: ["triceps", "shoulders"],
      instructions: [
        "Lie on a decline bench with your feet secured and your head lower than your hips.",
        "Grasp the barbell with an overhand grip slightly wider than shoulder-width apart.",
        "Unrack the barbell and lower it slowly towards your chest, keeping your elbows tucked in.",
        "Pause for a moment at the bottom, then push the barbell back up to the starting position.",
        "Repeat for the desired number of repetitions.",
      ],
    },
    {
      bodyPart: "chest",
      equipment: "barbell",
      gifUrl: "https://v2.exercisedb.io/image/JjAqrrWu6WL98o",
      id: "1255",
      name: "barbell decline pullover",
      target: "pectorals",
      secondaryMuscles: ["triceps", "shoulders"],
      instructions: [
        "Lie down on a decline bench with your head lower than your hips and your feet secured.",
        "Hold the barbell with a pronated grip (palms facing away from you) and your hands slightly wider than shoulder-width apart.",
        "Extend your arms above your chest, keeping a slight bend in your elbows.",
        "Lower the barbell in an arc motion behind your head, feeling a stretch in your chest and shoulders.",
        "Pause for a moment, then return the barbell to the starting position by reversing the motion.",
        "Repeat for the desired number of repetitions.",
      ],
    },
    {
      bodyPart: "chest",
      equipment: "barbell",
      gifUrl: "https://v2.exercisedb.io/image/RSf84MsQSpBsQQ",
      id: "0036",
      name: "barbell decline wide-grip press",
      target: "pectorals",
      secondaryMuscles: ["triceps", "shoulders"],
      instructions: [
        "Lie on a decline bench with your feet secured and your head lower than your hips.",
        "Grasp the barbell with a wide grip, slightly wider than shoulder-width apart.",
        "Lower the barbell to your chest, keeping your elbows out to the sides.",
        "Push the barbell back up to the starting position, fully extending your arms.",
        "Repeat for the desired number of repetitions.",
      ],
    },
  ],
};
